/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAssignmentsIndexRouteImport } from './routes/dashboard/assignments/index'
import { Route as DashboardLearnerMapAssignmentIdRouteImport } from './routes/dashboard/learner-map/$assignmentId'
import { Route as DashboardGoalMapGoalMapIdRouteImport } from './routes/dashboard/goal-map.$goalMapId'
import { Route as DashboardAssignmentsManageRouteImport } from './routes/dashboard/assignments/manage'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardLearnerMapAssignmentIdResultRouteImport } from './routes/dashboard/learner-map/$assignmentId.result'
import { Route as ApiMaterialsImagesGoalMapIdImageIdRouteImport } from './routes/api/materials/images/$goalMapId/$imageId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsIndexRoute =
  DashboardAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLearnerMapAssignmentIdRoute =
  DashboardLearnerMapAssignmentIdRouteImport.update({
    id: '/learner-map/$assignmentId',
    path: '/learner-map/$assignmentId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGoalMapGoalMapIdRoute =
  DashboardGoalMapGoalMapIdRouteImport.update({
    id: '/goal-map/$goalMapId',
    path: '/goal-map/$goalMapId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAssignmentsManageRoute =
  DashboardAssignmentsManageRouteImport.update({
    id: '/assignments/manage',
    path: '/assignments/manage',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLearnerMapAssignmentIdResultRoute =
  DashboardLearnerMapAssignmentIdResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => DashboardLearnerMapAssignmentIdRoute,
  } as any)
const ApiMaterialsImagesGoalMapIdImageIdRoute =
  ApiMaterialsImagesGoalMapIdImageIdRouteImport.update({
    id: '/api/materials/images/$goalMapId/$imageId',
    path: '/api/materials/images/$goalMapId/$imageId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/assignments/manage': typeof DashboardAssignmentsManageRoute
  '/dashboard/goal-map/$goalMapId': typeof DashboardGoalMapGoalMapIdRoute
  '/dashboard/learner-map/$assignmentId': typeof DashboardLearnerMapAssignmentIdRouteWithChildren
  '/dashboard/assignments': typeof DashboardAssignmentsIndexRoute
  '/dashboard/learner-map/$assignmentId/result': typeof DashboardLearnerMapAssignmentIdResultRoute
  '/api/materials/images/$goalMapId/$imageId': typeof ApiMaterialsImagesGoalMapIdImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/assignments/manage': typeof DashboardAssignmentsManageRoute
  '/dashboard/goal-map/$goalMapId': typeof DashboardGoalMapGoalMapIdRoute
  '/dashboard/learner-map/$assignmentId': typeof DashboardLearnerMapAssignmentIdRouteWithChildren
  '/dashboard/assignments': typeof DashboardAssignmentsIndexRoute
  '/dashboard/learner-map/$assignmentId/result': typeof DashboardLearnerMapAssignmentIdResultRoute
  '/api/materials/images/$goalMapId/$imageId': typeof ApiMaterialsImagesGoalMapIdImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/assignments/manage': typeof DashboardAssignmentsManageRoute
  '/dashboard/goal-map/$goalMapId': typeof DashboardGoalMapGoalMapIdRoute
  '/dashboard/learner-map/$assignmentId': typeof DashboardLearnerMapAssignmentIdRouteWithChildren
  '/dashboard/assignments/': typeof DashboardAssignmentsIndexRoute
  '/dashboard/learner-map/$assignmentId/result': typeof DashboardLearnerMapAssignmentIdResultRoute
  '/api/materials/images/$goalMapId/$imageId': typeof ApiMaterialsImagesGoalMapIdImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/assignments/manage'
    | '/dashboard/goal-map/$goalMapId'
    | '/dashboard/learner-map/$assignmentId'
    | '/dashboard/assignments'
    | '/dashboard/learner-map/$assignmentId/result'
    | '/api/materials/images/$goalMapId/$imageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/profile'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/assignments/manage'
    | '/dashboard/goal-map/$goalMapId'
    | '/dashboard/learner-map/$assignmentId'
    | '/dashboard/assignments'
    | '/dashboard/learner-map/$assignmentId/result'
    | '/api/materials/images/$goalMapId/$imageId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/assignments/manage'
    | '/dashboard/goal-map/$goalMapId'
    | '/dashboard/learner-map/$assignmentId'
    | '/dashboard/assignments/'
    | '/dashboard/learner-map/$assignmentId/result'
    | '/api/materials/images/$goalMapId/$imageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMaterialsImagesGoalMapIdImageIdRoute: typeof ApiMaterialsImagesGoalMapIdImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments/': {
      id: '/dashboard/assignments/'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/learner-map/$assignmentId': {
      id: '/dashboard/learner-map/$assignmentId'
      path: '/learner-map/$assignmentId'
      fullPath: '/dashboard/learner-map/$assignmentId'
      preLoaderRoute: typeof DashboardLearnerMapAssignmentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/goal-map/$goalMapId': {
      id: '/dashboard/goal-map/$goalMapId'
      path: '/goal-map/$goalMapId'
      fullPath: '/dashboard/goal-map/$goalMapId'
      preLoaderRoute: typeof DashboardGoalMapGoalMapIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments/manage': {
      id: '/dashboard/assignments/manage'
      path: '/assignments/manage'
      fullPath: '/dashboard/assignments/manage'
      preLoaderRoute: typeof DashboardAssignmentsManageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/learner-map/$assignmentId/result': {
      id: '/dashboard/learner-map/$assignmentId/result'
      path: '/result'
      fullPath: '/dashboard/learner-map/$assignmentId/result'
      preLoaderRoute: typeof DashboardLearnerMapAssignmentIdResultRouteImport
      parentRoute: typeof DashboardLearnerMapAssignmentIdRoute
    }
    '/api/materials/images/$goalMapId/$imageId': {
      id: '/api/materials/images/$goalMapId/$imageId'
      path: '/api/materials/images/$goalMapId/$imageId'
      fullPath: '/api/materials/images/$goalMapId/$imageId'
      preLoaderRoute: typeof ApiMaterialsImagesGoalMapIdImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardLearnerMapAssignmentIdRouteChildren {
  DashboardLearnerMapAssignmentIdResultRoute: typeof DashboardLearnerMapAssignmentIdResultRoute
}

const DashboardLearnerMapAssignmentIdRouteChildren: DashboardLearnerMapAssignmentIdRouteChildren =
  {
    DashboardLearnerMapAssignmentIdResultRoute:
      DashboardLearnerMapAssignmentIdResultRoute,
  }

const DashboardLearnerMapAssignmentIdRouteWithChildren =
  DashboardLearnerMapAssignmentIdRoute._addFileChildren(
    DashboardLearnerMapAssignmentIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAssignmentsManageRoute: typeof DashboardAssignmentsManageRoute
  DashboardGoalMapGoalMapIdRoute: typeof DashboardGoalMapGoalMapIdRoute
  DashboardLearnerMapAssignmentIdRoute: typeof DashboardLearnerMapAssignmentIdRouteWithChildren
  DashboardAssignmentsIndexRoute: typeof DashboardAssignmentsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAssignmentsManageRoute: DashboardAssignmentsManageRoute,
  DashboardGoalMapGoalMapIdRoute: DashboardGoalMapGoalMapIdRoute,
  DashboardLearnerMapAssignmentIdRoute:
    DashboardLearnerMapAssignmentIdRouteWithChildren,
  DashboardAssignmentsIndexRoute: DashboardAssignmentsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMaterialsImagesGoalMapIdImageIdRoute:
    ApiMaterialsImagesGoalMapIdImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
